ifeq ($(TAURUS_TARGET),THEJAS32)
$(info TARGET:  THEJAS32 Hardware)
RISCV_ARCH=rv32im
RISCV_ABI=ilp32
XLEN=32
else ifeq ($(TAURUS_TARGET),THEJAS64)
$(info TARGET:  THEJAS64 Hardware)
RISCV_ARCH=rv64ima
RISCV_ABI=lp64
XLEN=64
else ifeq ($(TAURUS_TARGET),CDACFPGA)
$(info TARGET: CDAC FPGA Board)
RISCV_ARCH=rv64imafd
RISCV_ABI=lp64d
XLEN=64
else
$(error Target $(TAURUS_TARGET) is invalid.)
endif